name: Post Daily Random SCP

on:
    workflow_dispatch:
    schedule:
        # 00:15 every sunday
        - cron: "15 0 * * 0"
jobs:
    post:
        name: Daily Random SCP Workflow
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"

            - name: "Set up uv"
              uses: astral-sh/setup-uv@v6

            - name: "Install Dependencies"
              run: uv sync --locked

            # generate 7 random scps and queue them
            - run: uv run main.py --count 7
              env:
                  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
                  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
                  OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
                  OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
